-- Company research cache: shared across all users, generated by AI on first lookup
CREATE TABLE companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  name_normalized TEXT NOT NULL UNIQUE,  -- lowercase, used for dedup and exact lookup
  research JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TRIGGER set_companies_updated_at
  BEFORE UPDATE ON companies
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Partial name search (ILIKE %query%)
CREATE INDEX companies_name_normalized_idx ON companies (name_normalized text_pattern_ops);

-- RLS: all authenticated users can read; backend service role handles writes
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read companies"
  ON companies FOR SELECT
  TO authenticated
  USING (true);
